<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Components\Shared\" />
    <Folder Include="Components\Pages\Auth\" />
    <Folder Include="Components\Pages\Employee\" />
    <Folder Include="Models\" />
    <Folder Include="Services\Auth\" />
  </ItemGroup>

</Project>
